import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@theme/theme";
import { ChildrenOnly } from "@models/dataModel";
import { StoreProvider } from "@redux/StoreProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Powell",
  description: "Generated by create next app",
};

const RootLayout = ({children}: ChildrenOnly) => (
    <StoreProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={inter.className}>
            {children}
          </body>
        </html>
      </ThemeProvider>
    </StoreProvider>
);

export default RootLayout;
